### ISSUE TITLE
Multiple TOTP Code

### ISSUE THREAD

**Issue by hashmesan** [hashmesan/harmony-totp#3]
# Motivation

6 digit TOTP Code provides 1million combination.  If the hashes are stolen, the TOTP wallet could be vulnerable.  We propose to have multiple TOTP codes to strengthen the hashes.  At 2 TOTP code, 12 digit code, provides 10^12 combinations ~ 1 Trillion combinations.

Also check out https://en.wikipedia.org/wiki/Lamport_signature

**Comment by dionyziz** [comment]
A 12 digit code does not provide sufficient security. For 128-bit security, you need 39 digits, i.e. 7 OTPs.

**Comment by dionyziz** [comment]
For reference, a simple consumer commercially available GPU can be used to brute force the 6 digit OTP in 0.000056 seconds, and a 12 digit OTP in under a minute. If the hashes are compromised, the attacker has direct full access to the wallet effortlessly.

[Benchmark here](https://github.com/siseci/hashcat-benchmark-comparison/blob/master/4x%20Nvidia%20GTX%201080%20TI%20Hashcat%20Benchmark).

**Comment by hashmesan** [comment]
Implemented with 5 Codes in ownerkey branch.  6 x 5 = 30 digits ~ 100 bits. of entropy
