### ISSUE TITLE
Unable to open App on Android

### ISSUE THREAD

**Issue by kennybetz** [hashmesan/harmony-totp#73]
Getting white screen when opening. Had Beta, deleted reinstalled, then deleted reinstalled latest stable with no luck. Android v12 Pixel 4.

**Comment by hashmesan** [comment]
Thank you for report. We're investigating this.

**Comment by hashmesan** [comment]
Can I ask whether you saw at the app at all, and/or able to create a new wallet? Thanks

**Comment by hashmesan** [comment]
It's on the appstore (1.1.1  Build 13) build. Give it a try. Thank you

**Comment by kennybetz** [comment]
Excellent I will. The app logo would pop up and then it would fade to white and stayed a solid white screen.

**Comment by kennybetz** [comment]
Excellent, works. Guess it's time to upgrade the phone.
