### ISSUE TITLE
Problems Setting Up New Wallet

### ISSUE THREAD

**Issue by CharleyBAZ** [hashmesan/harmony-totp#74]
Hello, I have tried following the instructions 3-4 times to setup a new wallet. Each time I get to the page that indicates I need to make a deposit of at least .2 ONE. I make the deposit and nothing else happens.  

Do you have any additional instructional material or feedback that I can use to figure out the issue? 

Thanks

**Comment by hashmesan** [comment]
We havent had report like this.  Can you provide the address you sent? I
will check the tx details.  The blue button create wallet should enable
when you deposit correct amount.

**Comment by CharleyBAZ** [comment]
Hello,

I attached a screenshot of the transaction of sending to the Sef wallet
address.

Thanks for the help.

**Comment by CharleyBAZ** [comment]
![Screenshot_20211206-200259_Gallery](https://user-images.githubusercontent.com/83322624/144958793-d2b3f1aa-96b2-4091-89a4-18a6864f6ec9.jpg)

**Comment by hashmesan** [comment]
The transfer looks fine. Did you see the wallet screen in the app change? Can you show a screenshot of that? Thank you

**Comment by CharleyBAZ** [comment]
Hello, 

After making the deposit,  here is the screen that I see.  It just stays on this screen and doesn't change.. 
![Screenshot_20211207-055411_Gallery](https://user-images.githubusercontent.com/83322624/145032992-f00d7f49-7db6-46ae-aa90-8bda7e2b7be2.jpg)
Thanks

**Comment by x0f0f4e** [comment]
I see the problem. There is an issue with the sizing on your phone so it is obscuring the Button at the bottom.  We will push a hotfix then notify when it's on the appstore.

**Comment by hashmesan** [comment]
I see the problem. There is an issue with the sizing on your phone so it is obscuring the Button at the bottom. We will push a hotfix then notify when it's on the appstore.

**Comment by hashmesan** [comment]
It's on the appstore (1.1.1 #13) build. Give it a try. Thank you

**Comment by CharleyBAZ** [comment]
Hello, yes...I was successful with the wallet install.  Thanks for the help

**Comment by hashmesan** [comment]
@CharleyBAZ  great. we'll make it better for smaller screens. Feel free to report any issues (even minor ones).  I noticed #75  issue. It felt a little small to scroll the assets.
