### ISSUE TITLE
Problem when selecting an asset

### ISSUE THREAD

**Issue by CharleyBAZ** [hashmesan/harmony-totp#81]
Hello, 

When I select one of the assets from the wallets home screen, it transitions to the asset page and then reverts to the screen shot page.  When I hit the back button on my phone the wallet closes. 

Samsung Galaxy S11

Start here. Select an asset. 
![Screenshot_20211214-211924_Sef](https://user-images.githubusercontent.com/83322624/146122866-67969e6f-2cf6-475c-9237-d2001a43c418.jpg)

This screen comes up. 
![Screenshot_20211214-211912_Sef](https://user-images.githubusercontent.com/83322624/146122882-b9769cf0-fba4-4cd4-a037-1d785c398fae.jpg)

**Comment by hashmesan** [comment]
Confirmed issue. It must of broke between release. will be fixed in this week's release

**Comment by hashmesan** [comment]
Released on 1.2.0. Be in playstore in 24h
