### ISSUE TITLE
Sefwallet

### ISSUE THREAD

**Issue by Tbonaventura** [hashmesan/harmony-totp#84]
I continue to have issues withdrawing from sefwallet to MetaMask wallet.  It continues to timeout.

**Comment by hashmesan** [comment]
The whole network has been having issues with RPC and fees. We just pushed the gas up. If you are seeing network fee 0.006. Then that should be the correct one to get it through.   Android, we're pushing a build -- will be available in 24 hrs.

**Comment by Tbonaventura** [comment]
I am using the iPhone app and it is at .002

**Comment by hashmesan** [comment]
It should work at 0.002 as well.  Can you confirm your build version from settings?  Restart the app also help it gets the new configs.

**Comment by Tbonaventura** [comment]
Version is 1.20#13 and the error is transaction underpriced

**Comment by hashmesan** [comment]
That is a good version. Try to restart the app and see if you can confirm new gas price. thx

**Comment by Tbonaventura** [comment]
I am now receding a transaction underpriced

**Comment by hashmesan** [comment]
It is working for me. It has to do with gas price being sett. On the app launch , it gets the new gas price for your transaction.   You restarted the app, and still having issue?

**Comment by Tbonaventura** [comment]
I am continuing to receive a transaction underpriced error

**Comment by Tbonaventura** [comment]
![1D8613CC-99C3-44DE-BFEB-6E0FB44F2615](https://user-images.githubusercontent.com/97903185/150096107-b6e607bb-c4cd-4209-8bb2-93baa2ad4d2d.png)

**Comment by hashmesan** [comment]
The old config may have been cached. We disabled the cache and switched the RPC. Give it a try. Thank you!

**Comment by Tbonaventura** [comment]
Transfer completed. The iOS app was still at .003 and now shows .007.  Thank you so much
