### ISSUE TITLE
Error code 502

### ISSUE THREAD

**Issue by Tbonaventura** [hashmesan/harmony-totp#85]
What is a error 502 when sending coins out

**Comment by hashmesan** [comment]
It's probably related to the partner RPC service pokt we used. We switched back to official RPC. Try restarting the app again.

CORRECTION: Tracking the 502 code deeper.  Some issues with new API.

**Comment by hashmesan** [comment]
The RPC kept crashing our relayer. We fixed the problem.

**Comment by Tbonaventura** [comment]
Thank you so much that cleared up
