### ISSUE TITLE
SEF Transfer Error Message

### ISSUE THREAD

**Issue by CharleyBAZ** [hashmesan/harmony-totp#88]
Hello, when I tried to transfer ONE from SEF to another wallet, I get this error and then another time the wallet screen just disappeared when I hit the continue button.  I am on  a Samsung Galaxy S20. Can you advise
![Screenshot_20220326-130154_Sef](https://user-images.githubusercontent.com/83322624/160255686-a5bcd230-7886-4535-b753-f8a25c9a526b.jpg)
?

**Comment by Minglesp** [comment]
I’m getting the same thing.  Anyone fix this yet ?

**Comment by hashmesan** [comment]
Are you using the newly upgraded wallet? What wallet version?

**Comment by CharleyBAZ** [comment]
This is occurring using 1.3.4 #20

**Comment by hashmesan** [comment]
Android or iOS ? thanks

**Comment by CharleyBAZ** [comment]
Android

**Comment by Minglesp** [comment]
I’m not sure. How do I check that

**Comment by Minglesp** [comment]
I just downloaded the app

**Comment by CharleyBAZ** [comment]
I don't understand why it is 2 weeks since this was posted and still no feedback or suggestions.  I tried again and got the same error message. 

Please advise.

![Screenshot_20220408-181551_Sef](https://user-images.githubusercontent.com/83322624/162550935-3aee601f-984b-4e14-874d-4b2823b34559.jpg)

![Screenshot_20220408-181512_Sef](https://user-images.githubusercontent.com/83322624/162550960-6573bfef-786f-48df-ad66-073609adf69b.jpg)

![Screenshot_20220408-181527_Sef](https://user-images.githubusercontent.com/83322624/162550967-15ddbaf1-5d5e-4d8e-8126-f629a86b17c2.jpg)

**Comment by CharleyBAZ** [comment]
As of this date, I still cannot transfer ONE out of you wallet. Please advise.

**Comment by hashmesan** [comment]
I think there was a bug with migration process. Is your balance just 4 ONE because we can compensate that and take more time to fix?

**Comment by CharleyBAZ** [comment]
Its not the amount obviously, it's the fact that, what if, I sent thousands of dollars to the wallet?  To my knowledge, you have not presented the wallet as in experimental or beta stage...it has been promoted as a fully functioning product.  You wallet says to report issues here, and here we are three weeks with no solution...it is frustrating because I have promoted the SEF wallet.  I was excited about it and it seems the team has not been forthright about its available use by the public.  Now, I would not dare send any large amount of money to it.   I am prepared to be corrected, If I missed something but if I keep pretty good track on these things.

**Comment by Minglesp** [comment]
I'm having the same issue

**Comment by hashmesan** [comment]
@CharleyBAZ Thank you for the context. I really appreciate you working with us to improve the app. The app is well tested, but there were some edge cases we didn't account for when it is deployed, esp for users migrating from older apps. These edge cases are hard to track down since we need to install the older one, and figure out how to recreate the same issue you had, which we haven't yet. 

The two accounts sharing the address is strange.  The error implies that i thinks the vault is a regular address or vise-versa. I think if you reset the app from settings (the vault will retain), then create/restore classic wallet.   Let's see if you see two different addresses on the left tab.

**Comment by CharleyBAZ** [comment]
I reset the app, which erased the classic balance/wallet and kept the same vault wallet.  I then imported the wallet address with 4 ONE in it and tried to transfer the funds but still got the same error message indicated above.

**Comment by hashmesan** [comment]
Fix coming soon.... It was introduced when we implemented staking transactions.

**Comment by hashmesan** [comment]
Bug fix released on 1.3.5 , should between now and a few hours for android, 24hr for iOS

**Comment by CharleyBAZ** [comment]
Thank you.  This update has resolved the issue and I can now transfer funds out of the wallet.
